config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  resources :orders
  resources :line_items
  resources :carts
  get '/geochart', to: 'geochart#index'
  get '/chart1', to: 'chart1#index'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/access_denied', to: 'access_denied#index'
  resources :users
  resources :eruptions
  resources :uniq_volcanos
  root 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  include RailsAdminCharts

  def add_volcano(volcano)
    current_item = line_items.find_by(uniq_volcano_id: volcano.id)
    if current_item
      return nil
    else
      current_item = line_items.build(uniq_volcano_id: volcano.id)
      return current_item
    end
  end
end

app/models/eruption.rb
class Eruption < ApplicationRecord
  belongs_to :uniq_volcano, optional: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :uniq_volcano, optional: true
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  include RailsAdminCharts
  validates :name, :email, presence: true
  has_many :line_items, dependent: :destroy

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/uniq_volcano.rb
class UniqVolcano < ApplicationRecord
  include RailsAdminCharts
  has_many :eruption
  has_many :line_item

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include RailsAdminCharts
  validates :name, presence: true, length: {maximum: 50}, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 75},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, on: :create
  validates :password, length: {minimum: 6}, allow_blank: true, on: :update
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html {redirect_to @cart, notice: 'Cart was successfully created.'}
        format.json {render :show, status: :created, location: @cart}
      else
        format.html {render :new}
        format.json {render json: @cart.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html {redirect_to @cart, notice: 'Cart was successfully updated.'}
        format.json {render :show, status: :ok, location: @cart}
      else
        format.html {render :edit}
        format.json {render json: @cart.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html {redirect_to uniq_volcanos_url, notice: 'Cart was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/uniq_volcanos_controller.rb
class UniqVolcanosController < ApplicationController
  before_action :set_uniq_volcano, only: [:show, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart
  # GET /uniq_volcanos
  # GET /uniq_volcanos.json
  def index
    @uniq_volcanos = UniqVolcano.all
  end

  # GET /uniq_volcanos/1
  # GET /uniq_volcanos/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_uniq_volcano
    @uniq_volcano = UniqVolcano.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def uniq_volcano_params
    params.require(:uniq_volcano).permit(:Name, :Location, :Country, :Latitude, :Longitude, :Elevation, :Type, :Status, :Time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :logged_in?, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html {redirect_to '/', notice: 'User #{@user.name} was successfully created.'}
        format.json {render :show, status: :created, location: @user}
      else
        format.html {render :new}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to users_url, notice: 'User #{@user.name} was successfully updated.'}
        format.json {render :show, status: :ok, location: @user}
      else
        format.html {render :edit}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_url, notice: 'User was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/chart1_helper.rb
module Chart1Helper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/eruptions_helper.rb
module EruptionsHelper
end

app/helpers/geochart_helper.rb
module GeochartHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    if User.find_by(id: session[:user_id])
      return true
    end
  end

  def admin?
    unless current_user.admin == true || current_user.name == "admin"
      return false
    else
      return true
    end
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
    if @cart
      @cart.destroy
    end
  end
end

app/helpers/uniq_volcanos_helper.rb
module UniqVolcanosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/uniq_volcanos/_form.html.erb
<%= form_with(model: uniq_volcano, local: true) do |form| %>
  <% if uniq_volcano.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uniq_volcano.errors.count, "error") %> prohibited this uniq_volcano from being saved:</h2>

      <ul>
        <% uniq_volcano.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_area :Name %>
  </div>

  <div class="field">
    <%= form.label :Location %>
    <%= form.text_area :Location %>
  </div>

  <div class="field">
    <%= form.label :Country %>
    <%= form.text_area :Country %>
  </div>

  <div class="field">
    <%= form.label :Latitude %>
    <%= form.text_field :Latitude %>
  </div>

  <div class="field">
    <%= form.label :Longitude %>
    <%= form.text_field :Longitude %>
  </div>

  <div class="field">
    <%= form.label :Elevation %>
    <%= form.number_field :Elevation %>
  </div>

  <div class="field">
    <%= form.label :Type %>
    <%= form.text_area :Type %>
  </div>

  <div class="field">
    <%= form.label :Status %>
    <%= form.text_area :Status %>
  </div>

  <div class="field">
    <%= form.label :Time %>
    <%= form.text_area :Time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uniq_volcanos/index.html.erb
<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
<div class="sidebar">
  <% if @cart %>
    <%= render @cart %>
    <div class="actions">
      <%= button_to 'Empty cart', @cart, method: :delete,
                    data: {confirm: 'Are you sure?'}, class: "w3-button w3-ripple w3-black w3-hover-blue w3-round-xxlarge" %>
      <%= button_to 'Checkout', new_order_path, method: :get, class: "checkout w3-button w3-ripple w3-black w3-hover-blue w3-round-xxlarge" %>
    </div>
  <% end %>
</div>
<div class="volcanowrap">
  <h1>Volcanoes!</h1>
  <p>Here you can browse our catalogue of volcanoes for sale!</p>
  <div id="volcanoes">
    <table id="catalog" class="w3-table w3-striped" style="margin-right:25%;">
      <input class="search" placeholder="Search"/>
      <button class="sort w3-button w3-black w3-round-xxlarge w3-ripple w3-hover-blue" data-sort="name">
        Sort by name
      </button>
      <button class="sort w3-button w3-black w3-round-xxlarge w3-ripple w3-hover-blue" data-sort="country">
        Sort by country
      </button>
      <button class="sort w3-button w3-black w3-round-xxlarge w3-ripple w3-hover-blue" data-sort="elevation">
        Sort by elevation
      </button>
      <button class="sort w3-button w3-black w3-round-xxlarge w3-ripple w3-hover-blue" data-sort="price">
        Sort by price
      </button>
      <thead>
      <tr>
        <th>Name</th>
        <th>Country</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Elevation</th>
        <th>Price</th>
        <th>Status</th>
        <th>Time</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody class="list">
      <% @uniq_volcanos.each do |uniq_volcano| %>
        <tr>
          <td class="name"><%= link_to uniq_volcano.Name, uniq_volcano %></td>
          <td class="country"><%= uniq_volcano.Country %></td>
          <td class="latitude"><%= uniq_volcano.Latitude %></td>
          <td class="longitude"><%= uniq_volcano.Longitude %></td>
          <td class="elevation"><%= uniq_volcano.Elevation %></td>
          <td class="type"><%= uniq_volcano.Type %></td>
          <td class="status"><%= uniq_volcano.Status %></td>
          <td class="price"><%= uniq_volcano.Price / 1000 %>k$</td>
          <td><%= button_to 'Add to Cart', line_items_path(uniq_volcano_id: uniq_volcano), remote: true, class: "w3-button w3-ripple w3-black w3-hover-blue w3-round-xxlarge" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <br>

</div>
<script>
    var options = {
        valueNames: ['name', 'country', 'elevation', 'price']
    };

    var userList = new List('volcanoes', options);
</script>

app/views/uniq_volcanos/show.html.erb
<div class="sidebar">
  <% if @cart %>
    <%= render @cart %>
    <div class="actions">
      <%= button_to 'Empty cart', @cart, method: :delete,
                    data: {confirm: 'Are you sure?'}, class: "w3-button w3-ripple w3-black w3-hover-blue w3-round-xxlarge" %>
      <%= button_to 'Checkout', new_order_path, method: :get, class: "checkout w3-button w3-ripple w3-black w3-hover-blue w3-round-xxlarge" %>
    </div>
  <% end %>
</div>
<div class="w3-row">
  <div class="w3-col m5">
    <p>
      <strong>Name:</strong>
      <%= @uniq_volcano.Name %>
    </p>

    <p>
      <strong>Country:</strong>
      <%= @uniq_volcano.Country %>
    </p>

    <p>
      <strong>Latitude:</strong>
      <%= @uniq_volcano.Latitude %>
    </p>

    <p>
      <strong>Longitude:</strong>
      <%= @uniq_volcano.Longitude %>
    </p>

    <p>
      <strong>Elevation:</strong>
      <%= @uniq_volcano.Elevation %>
    </p>

    <p>
      <strong>Type:</strong>
      <%= @uniq_volcano.Type %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @uniq_volcano.Status %>
    </p>

    <p>
      <strong>Time:</strong>
      <%= @uniq_volcano.Time %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @uniq_volcano.Price %>$
    </p>
  </div>
  <div class="w3-col m3">
    <h3>Recorded eruptions of this volcano:</h3>
    <% @uniq_volcano.eruption.each do |eruption| %>
      <p>
        <%= link_to eruption.Year, eruption %>
      </p>
    <% end %>
  </div>


</div>
</div>
<div class="w3-row">
  <%= link_to 'Back', uniq_volcanos_path, class: "w3-button w3-ripple w3-black w3-hover-blue w3-round-xxlarge" %>
  <%= button_to 'Add to Cart', line_items_path(uniq_volcano_id: @uniq_volcano), remote: true, class: "w3-button w3-ripple w3-black w3-hover-blue w3-round-xxlarge", style: "position: relative; right: 0" %>
</div>